name       : libusbmuxd
version    : 2.0.2
release    : 6
source     :
    - git|https://github.com/libimobiledevice/libusbmuxd.git : f26cb457954f129850c265060b84000128839c5a
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : A client library to multiplex connections from and to iOS devices by
    connecting to a socket provided by a usbmuxd daemon.
description: |
    A client library to multiplex connections from and to iOS devices by connecting to a socket provided by a usbmuxd daemon.
builddeps  :
    - pkgconfig(libplist-2.0)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
