name       : libusbmuxd
version    : 1.0.10
release    : 1
source     :
    - http://www.libimobiledevice.org/downloads/libusbmuxd-1.0.10.tar.bz2 : 1aa21391265d2284ac3ccb7cf278126d10d354878589905b35e8102104fec9f2
license    : LGPL-2.1
summary    : A client library to multiplex connections from and to iOS devices by connecting to a socket provided by a usbmuxd daemon.
description: |
    A client library to multiplex connections from and to iOS devices by connecting to a socket provided by a usbmuxd daemon.
builddeps  :
    - pkgconfig(libplist)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
